name: md_thesis_app
description: "A Md Thesis Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependency_overrides:
  web: 1.0.0
  geolocator_apple: 2.2.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  mockito: ^5.1.0
  bloc_test: ^9.0.3
  flutter_modular: ^6.1.1
  formz: ^0.6.1
  styled_text: ^8.1.0
  bloc_presentation: ^1.0.0
  shared_preferences: ^2.3.2
  drift: ^2.18.0
  path: ^1.9.0
  device_info_plus: 9.1.2 #Higher versions not recommended. Requires Java 17 which we do not support
  package_info_plus: 5.0.1 #Higher versions not recommended. Requires Java 17 which we do not support
  flutter_map: 7.0.2 #For safety of the project manually check behavior of the app before upgrading this package. Do not auto update!
  flutter_map_cache: 1.5.1 #For safety of the project manually check behavior of the app before upgrading this package. Do not auto update!
  dio_cache_interceptor_hive_store: 3.2.2 #For safety of the project manually check behavior of the app before upgrading this package. Do not auto update!
  flutter_map_location_marker: 9.0.0
  geolocator: 12.0.0 #For safety of the project manually check behavior of the app before upgrading this package. Do not auto update!
  fl_chart: ^0.69.0
  flutter_screenutil: ^5.9.3
  flutter_hooks: ^0.20.5
  google_maps_flutter: 2.9.0
  apple_maps_flutter: 1.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.4.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  generate: true
